import Head from 'next/head'
import Navbar from '../components/navbar'
import List from '../components/List';
import Image from 'next/image';
import love from '../public/love.jpg'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Navbar />
      <List />
      <div className='text-center mt-16'>
        <Image
          src={love}
          alt="back"
          width={500}
          height={300}
        />
      </div>
      <div className='text-center mt-16'>
        <Image
          src={love}
          alt="back"
          objectFit="contain"
        />
      </div>
    </div>
  )
}
